sudo: true
language: c
services:
- docker

# This is a hook to help us introduce "soft" errors on our process
matrix:
  allow_failures:
    env: ALLOW_SOFT_FAILURE_HERE=true

# Install dependencies for all, once
#
install:
- sudo apt-get install -y libcap2-bin zlib1g-dev uuid-dev fakeroot libipmimonitoring-dev libmnl-dev libnetfilter-acct-dev gnupg python-pip
- source tests/installer/slack.sh

# Setup notification system
#
notifications:
  webhooks: https://app.fossa.io/hooks/travisci

# Define the stage sequence and conditionals
#
stages:
# Mandatory runs, we always want these executed
- name: Code quality, linting, syntax, code style
- name: Build process
- name: Artifacts validation

  # Nightly operations
- name: Nightly operations
  if: branch = master AND type = cron
- name: Nightly release
  if: branch = master AND type = cron

  # Scheduled releases
- name: Packaging for release
  if: branch = master AND type != pull_request AND type != cron
- name: Publish for release
  # We run this step on every commit on master, not cron, not PR AND there is a TAG set by the packaging step
  if: branch = master AND type != pull_request AND type != cron AND tag IS present AND NOt (tag =~ -rc*)



# Define stage implementation details
#
jobs:
  include:
    # Do code quality, syntax checking and other pre-build activities
  - stage: Code quality, linting, syntax, code style

    name: Run shellchecking on BASH
    script: shellcheck --format=gcc $(find . -name '*.sh.in' -not -iwholename '*.git*')

    # This falls under same stage defined earlier
  - name: Run checksum checks on kickstart files
    script: ./tests/installer/checksums.sh
    env: LOCAL_ONLY="true"

    # This falls under same stage defined earlier
  - name: Web Dashboard pre-generated file consistency checks (dashboard.js)
    script: cp web/gui/dashboard.js /tmp/dashboard.js && ./build/build.sh && diff /tmp/dashboard.js web/gui/dashboard.js



    # Ensure netdata code builds successfully
  - stage: Build process

    name: Standard netdata build
    script: fakeroot ./netdata-installer.sh --install $HOME --dont-wait --dont-start-it --enable-plugin-nfacct --enable-plugin-freeipmi --disable-lto
    env: CFLAGS='-O1 -DNETDATA_INTERNAL_CHECKS=1 -DNETDATA_VERIFY_LOCKS=1'
    after_failure: post_message "TRAVIS_MESSAGE" "@here standard netdata build is failing (Still dont know which one, will improve soon)"

  - name: Docker container build process (alpine installation)
    script: packaging/docker/build.sh
    env: DEVEL="true"
    after_failure: post_message "TRAVIS_MESSAGE" ""

  - name: Run 'make dist' validation
    before_script: mkdir /tmp/netdata-makedist-test
    script:
    - docker run -it -v "${PWD}:/code:rw" -v "/tmp/netdata-makedist-test:/netdata_install:rw" -w /code "netdata/os-test:ubuntu1804" make clean || echo "Nothing to clean"
    - docker run -it -v "${PWD}:/code:rw" -v "/tmp/netdata-makedist-test:/netdata_install:rw" -w /code "netdata/os-test:ubuntu1804" make distclean || echo "Nothing to distclean"
      #- docker run -it -v "${PWD}:/code:rw" -v "/tmp/netdata-makedist-test:/netdata_install:rw" -w /code "netdata/os-test:ubuntu1804" autoreconf -ivf && ./configure --prefix=/netdata_install/usr --sysconfdir=/netdata_install/etc --localstatedir=/netdata_install/var --with-zlib --with-math --with-user=netdata CFLAGS=-O2
      #- docker run -it -v "${PWD}:/code:rw" -v "/tmp/netdata-makedist-test:/netdata_install:rw" -w /code "netdata/os-test:ubuntu1804" make dist
      #- docker run -it -v "${PWD}:/code:rw" -v "/tmp/netdata-makedist-test:/netdata_install:rw" -w /code "netdata/os-test:ubuntu1804" ls -ltr ./netdata-v*.*.*.tar.gz
      #- docker run -it -v "${PWD}:/code:rw" -v "/tmp/netdata-makedist-test:/netdata_install:rw" -w /code "netdata/os-test:ubuntu1804" make distclean
    after_script: rm -rf /tmp/netdata-makedist-test
    after_failure: post_message "TRAVIS_MESSAGE" "'make dist' failed"



  - stage: Artifacts validation

    name: Unit Testing
    script:
    - fakeroot ./netdata-installer.sh --install $HOME --dont-wait --dont-start-it --enable-plugin-nfacct --enable-plugin-freeipmi --disable-lto
    - $HOME/netdata/usr/sbin/netdata -W unittest
    env: CFLAGS='-O1 -DNETDATA_INTERNAL_CHECKS=1 -DNETDATA_VERIFY_LOCKS=1'
    after_failure: post_message "TRAVIS_MESSAGE" "Unit testing failed"
    after_success: post_message "TRAVIS_MESSAGE" "Unit testing successful"

  - name: Build/install on ubuntu 14.04 (not containerized)
    script: fakeroot ./netdata-installer.sh --dont-wait --dont-start-it --install $HOME
    after_failure: post_message "TRAVIS_MESSAGE" "Build/Install failed on ubuntu 14.04"

  - name: Build/Install for ubuntu 18.04 (not containerized)
    script: fakeroot ./netdata-installer.sh --dont-wait --dont-start-it --install $HOME
    after_failure: post_message "TRAVIS_MESSAGE" "Build/Install failed on ubuntu 18.04"

  - name: Run netdata lifecycle, on ubuntu 18.04 (Containerized)
    script: docker run -it -v "${PWD}:/code:rw" -w /code "netdata/os-test:ubuntu1804" bats --tap tests/lifecycle.bats
    after_failure: post_message "TRAVIS_MESSAGE" "Netdata lifecycle test script failed on ubuntu 18.04"

  - name: Build/install for CentOS 6 (Containerized)
    script: docker run -it -v "${PWD}:/code:rw" -w /code "netdata/os-test:centos6" ./netdata-installer.sh --dont-wait --dont-start-it --install /tmp
    after_failure: post_message "TRAVIS_MESSAGE" "Build/Install failed on CentOS 6"

  - name: Build/install for CentOS 7 (Containerized)
    script: docker run -it -v "${PWD}:/code:rw" -w /code "netdata/os-test:centos7" ./netdata-installer.sh --dont-wait --dont-start-it --install /tmp
    after_failure: post_message "TRAVIS_MESSAGE" "Build/Install failed on CentOS 7"



  - stage: Packaging for release

    name: Generate changelog and TAG the release (only on special commit msg)
    install:
    - sudo apt install -y --only-upgrade docker-ce
    - sudo pip install git-semver
    - docker info
    before_script: post_message "TRAVIS_MESSAGE" "Packaging step for release initiated"
    script:
    - .travis/tagger.sh
    - .travis/generate_changelog_and_tag_release.sh
    after_failure: post_message "TRAVIS_MESSAGE" "@here Packaging for release failed"
    git:
      depth: false

  - name: Run labeler on github issues
    script: .travis/labeler.sh # labeler should be replaced with GitHub Actions when they hit GA



    # We only publish if a TAG has been set during packaging
  - stage: Publish for release

    git:
      depth: false
    name: Build & Publish docker images
    before_script: post_message "TRAVIS_MESSAGE" "Publishing docker images"
    script:
    - packaging/docker/build.sh
    - packaging/docker/publish.sh
    after_failure: post_message "TRAVIS_MESSAGE" "@here Docker image publishing failed"
    env: ALLOW_SOFT_FAILURE_HERE=true

  - name: Generate release artifacts
    before_script: post_message "TRAVIS_MESSAGE" "Starting artifacts generation for release"
    script: .travis/create_artifacts.sh
    after_failure: post_message "TRAVIS_MESSAGE" "@here Release artifacts generation failed"

  - name: Create release draft
    before_script: post_message "TRAVIS_MESSAGE" "Drafting release on github"
    script: .travis/draft_release.sh
    after_failure: post_message "TRAVIS_MESSAGE" "@here Draft release submission failed"



    # This is the nightly pre-execution step (Jobs, preparatory steps for nightly, etc)
  - stage: Nightly operations

    name: Run coverity scan
    # Just notify people that Nightly ops triggered, use the first step as a hook to do that
    before_script: post_message "TRAVIS_MESSAGE" "Starting nightly operations"
    script: ./coverity-install.sh && ./coverity-scan.sh || echo "Coverity failed :("

  - name: Kickstart files integrity testing (extended)
    script: ./tests/installer/checksums.sh

  - name: Run labeler on github issues
    script: .travis/labeler.sh # labeler should be replaced with GitHub Actions when they hit GA

    # This is generating the changelog for nightly release and publish it
  - name: Generate nightly changlog
    before_script: post_message "TRAVIS_MESSAGE" "Starting changelog generation for nightlies"
    script: ".travis/nightlies.sh"
    after_failure: post_message "TRAVIS_MESSAGE" "@here Nightly changelog generation failed"



    # This is the nightly execution step
    #
  - stage: Nightly release

    name: Build & Publish docker images
    install:
    - sudo apt install -y --only-upgrade docker-ce
    - docker info
    before_script: post_message "TRAVIS_MESSAGE" "Publishing docker images for nightlies"
    script:
    - packaging/docker/build.sh
    - packaging/docker/publish.sh
    after_failure: post_message "TRAVIS_MESSAGE" "@here Nightly docker image publish failed"
    env: ALLOW_SOFT_FAILURE_HERE=true

  - name: Create nightly release artifacts, publish to GCS
    before_script: post_message "TRAVIS_MESSAGE" "Starting artifacts generation for nightlies"
    script: .travis/create_artifacts.sh
    after_failure: post_message "TRAVIS_MESSAGE" "@here Nightly artifacts generation failed"
    git:
      depth: false
    before_deploy: openssl aes-256-cbc -K $encrypted_8daf19481253_key -iv $encrypted_8daf19481253_iv -in .travis/gcs-credentials.json.enc -out .travis/gcs-credentials.json -d
    deploy:
      provider: gcs
      edge:
        branch: gcs-ng
      project_id: netdata-storage
      credentials: .travis/gcs-credentials.json
      bucket: "netdata-nightlies"
      skip_cleanup: true
      local_dir: "artifacts"
    after_deploy: rm -f .travis/gcs-credentials.json
